# for local development
# local_backend: true
# site_url: http://localhost:8080

backend:
  name: git-gateway
  branch: develop

media_folder: /uploads
public_folder: /uploads
locale: en
# publish_mode: editorial_workflow

collections:
  - name: global-config
    label: Global configuration
    extension: json
    create: false
    delete: false
    slug: "{{slug}}"
    files:
      - name: config-global
        label: Global
        file: src/_data/config/global.json
        fields:
          - label: Company Name
            name: company
            widget: string
          - label: Company Subtitle
            name: companySub
            widget: string
          - label: Company Slogan
            name: slogan
            widget: string
            required: false

      - name: config-features
        label: Features
        file: src/_data/config/features.json
        fields:
          - label: Header
            name: header
            widget: string
          - label: Subheader
            name: subheader
            widget: string
            required: false

      - name: config-contact
        label: Contact
        file: src/_data/config/contact.json
        fields:
          - label: Success
            name: success
            widget: object
            fields:
              - label: Header
                name: header
                widget: string
              - label: Message
                name: message
                widget: string
              - label: Return button text
                name: button
                widget: string
          - label: Header
            name: header
            widget: string
          - label: Subheader
            name: subheader
            widget: string
            required: false
          - label: Address
            name: address
            widget: markdown
            required: false
          - label: Telephone
            name: telephone
            widget: string
            required: false
          - label: Email
            name: email
            widget: string
          - label: Twitter
            name: twitter
            widget: string
            required: false
          - label: LinkedIn
            name: linkedin
            widget: string
            required: false
          - label: Instagram
            name: instagram
            widget: string
            required: false

      - name: config-errors
        label: Errors
        file: src/_data/config/errors.json
        fields:
          - label: 404 Error
            name: http_404
            widget: object
            fields:
              - label: Header text
                name: header
                widget: string
              - label: Description
                name: description
                widget: string
              - label: Return button text
                name: button
                widget: string

  - name: services
    label: Services
    label_singular: Service
    folder: src/service
    create: true
    slug: "{{key}}"
    summary: "{{fields.title}}"
    fields:
      - label: Key
        name: key
        widget: string
        required: true
      - label: Order
        name: order
        widget: number
        default: 1
        value_type: int
        min: 1
        required: true
      - label: Title
        name: title
        widget: string
        required: true
      - label: Description
        name: description
        widget: markdown
        required: true
      - label: Image
        name: image
        widget: image
        required: true
      - label: Icon
        name: icon
        widget: string
        required: true

  - name: features
    label: Features
    label_singular: Feature
    folder: src/feature
    create: true
    slug: "{{key}}"
    summary: "{{fields.title}}"
    fields:
      - label: Key
        name: key
        widget: string
        required: true
      - label: Order
        name: order
        widget: number
        required: true
        default: -1
      - label: Title
        name: title
        widget: string
        required: true
      - label: Description
        name: description
        widget: markdown
        required: true
      - label: Image
        name: image
        widget: image
        required: true
